interface menuProps {
  nome: string
  nameSection: string | null
  id: number
  valor: string
}

export const dishes: menuProps[] = [
  {
    nome: 'Virado à Paulista - Segunda-feira',
    nameSection: 'Pratos do dia',
    id: 1,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Bife à rolê - Terça-feira',
    nameSection: null,
    id: 2,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Feijoada - Quarta-feira',
    nameSection: null,
    id: 3,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Macarrão com frango - Quinta-feira',
    nameSection: null,
    id: 4,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Filé de peixe - Sexta-feira',
    nameSection: null,
    id: 5,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Feijoada - Sábado',
    nameSection: null,
    id: 6,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Omelete',
    nameSection: 'Pratos executivos',
    id: 7,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Picadinho',
    nameSection: null,
    id: 8,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Fígado Acebolado',
    nameSection: null,
    id: 9,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Frango ao Molho',
    nameSection: null,
    id: 10,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Costela ao Molho',
    nameSection: null,
    id: 11,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Calabresa',
    nameSection: null,
    id: 12,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Bife Acebolado',
    nameSection: null,
    id: 13,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Bife à Milanesa',
    nameSection: null,
    id: 14,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Bife à Cavalo',
    nameSection: null,
    id: 15,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Frango à Passarinho',
    nameSection: null,
    id: 16,
    valor: 'A partir de: R$ 24,90',
  },
  {
    nome: 'Picanha',
    nameSection: 'Pratos especiais',
    id: 17,
    valor: 'A partir de: R$ 35,00',
  },
  {
    nome: 'Filé Mignon',
    nameSection: null,
    id: 18,
    valor: 'A partir de: R$ 32,00',
  },
  {
    nome: 'Contra Filé',
    nameSection: null,
    id: 19,
    valor: 'A partir de: R$ 32,00',
  },
  {
    nome: 'Parmegiana',
    nameSection: null,
    id: 20,
    valor: 'A partir de: R$ 35,00',
  },
  {
    nome: 'Strogonoff',
    nameSection: null,
    id: 21,
    valor: 'A partir de: R$ 35,00',
  },
  {
    nome: 'Filé de Frango Grelhado',
    nameSection: null,
    id: 22,
    valor: 'A partir de: R$ 32,00',
  },
  {
    nome: 'Filé de Frango à Milanesa',
    nameSection: null,
    id: 23,
    valor: 'A partir de: R$ 35,00',
  },
  {
    nome: 'Carne Assada c/ Molho Madero',
    nameSection: null,
    id: 24,
    valor: 'A partir de: R$ 35,00',
  },
  {
    nome: 'X-Salada',
    nameSection: 'Hambúrgueres & Beirutes',
    id: 25,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'X-Tudo',
    nameSection: null,
    id: 26,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'X-Bacon',
    nameSection: null,
    id: 27,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'X-Filé de Frango',
    nameSection: null,
    id: 28,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'X-Churrasco',
    nameSection: null,
    id: 29,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'Americano',
    nameSection: null,
    id: 30,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'Misto-Quente',
    nameSection: null,
    id: 31,
    valor: 'A partir de: R$ 8,00',
  },
  {
    nome: 'Queijo Quente',
    nameSection: null,
    id: 32,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'Beirute',
    nameSection: null,
    id: 33,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'Suco de Limão',
    nameSection: 'Bebidas',
    id: 34,
    valor: 'A partir de: R$ 9,00',
  },
  {
    nome: 'Água',
    nameSection: null,
    id: 35,
    valor: 'A partir de: R$ 2,00',
  },
  {
    nome: 'Suco Del Valle',
    nameSection: null,
    id: 36,
    valor: 'A partir de: R$ 5,00',
  },
  {
    nome: 'Refrigerante - Lata',
    nameSection: null,
    id: 37,
    valor: 'A partir de: R$ 5,00',
  },
  {
    nome: 'Refrigerante - Garrafa 2L',
    nameSection: null,
    id: 38,
    valor: 'A partir de: R$ 12,00',
  },
  {
    nome: 'Refrigerante - Garrafa 600ml',
    nameSection: null,
    id: 39,
    valor: 'A partir de: R$ 8,00',
  },
  {
    nome: 'Cerveja - Lata',
    nameSection: null,
    id: 40,
    valor: 'A partir de: R$ 6,00',
  },
  {
    nome: 'Cerveja - Garrafa 1L',
    nameSection: null,
    id: 41,
    valor: 'A partir de: R$ 14,00',
  },
  {
    nome: 'Cerveja - Garrafa 600ml',
    nameSection: null,
    id: 42,
    valor: 'A partir de: R$ 14,00',
  },
  {
    nome: 'Suco de Laranja',
    nameSection: null,
    id: 43,
    valor: 'A partir de: R$ 9,00',
  },
  {
    nome: 'Suco de Maracujá',
    nameSection: null,
    id: 44,
    valor: 'A partir de: R$ 9,00',
  },
  {
    nome: 'Suco de Abacaxi',
    nameSection: null,
    id: 45,
    valor: 'A partir de: R$ 9,00',
  },
  {
    nome: 'Caipirinha',
    nameSection: null,
    id: 46,
    valor: 'A partir de: R$ 17,00',
  },
  {
    nome: 'Cachaça',
    nameSection: null,
    id: 47,
    valor: 'A partir de: R$ 5,00',
  },
  {
    nome: 'Whisky',
    nameSection: null,
    id: 48,
    valor: 'A partir de: R$ 12,00',
  },
]
